.TH "DEBOPS-UPDATE" 1 "" "" "debops"
.SH NAME
\fBdebops-update\fP \- updates the collection of Ansible playbooks and roles from the DebOps project
.SH SYNOPSIS
$ \fBdebops-update\fP \fI<project_dir>\fP
.SH DESCRIPTION
The Debian package of DebOps works out of the box in combination with the officially
released collection of playbooks which is shipped in the separate package \fBdebops-playbooks\fP.
However, the latest snapshot could always be downloaded for individual projects with this tool.
.SH SEE ALSO
\fBdebops\fP(1),
\fBdebops-defaults\fP(1),
\fBdebops-init\fP(1),
\fBdebops-padlock\fP(1),
\fBdebops-task\fP(1)
.SH AUTHORS
DebOps is developed by Maciej Delmanowski <drybjed@gmail.com>,
Nick Janetakis <nick.janetakis@gmail.com>,
Hartmut Goebel <h.goebel@crazy-compilers.com>,
and Robin Schneider <ypid@riseup.net>.
.P
This manpage is written by Daniel Stender <stender@debian.org>.
